export const restaurantList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "666182",
      name: "China Bistro",
      uuid: "bd5614e1-eec8-4956-af44-40952bca4973",
      city: "5",
      area: "Chandivali",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "0e1a7c54a5623c38053ffa1ed6ab9630",
      cuisines: [
        "Chinese",
        "Asian",
        "Pan-Asian",
        "Sushi",
        "Japanese",
        "Oriental",
        "Desserts",
      ],
      tags: [],
      costForTwo: 75000,
      costForTwoString: "₹750 FOR TWO",
      deliveryTime: 64,
      minDeliveryTime: 64,
      maxDeliveryTime: 64,
      slaString: "64 MINS",
      lastMileTravel: 5,
      slugs: {
        restaurant: "china-bistro-saki-vihar-marol-sakinaka",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "Gala No. 7, Shree Guppi Industrial Estate, Saki Vihar Rd, Ganesh Nagar, Chandivali, Andheri East, Mumbai, Maharashtra 400072",
      locality: "Saki Vihar",
      parentId: 1871,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 6000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 6000,
        message: "",
        title: "Delivery Charge",
        amount: "6000",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7375272~p=1~eid=00000189-211a-d4dc-2f43-c8a700c7013e~srvts=1688477553884",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "ABOVE ₹1000",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "666182",
        deliveryTime: 64,
        minDeliveryTime: 64,
        maxDeliveryTime: 64,
        lastMileTravel: 5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "355806",
      name: "Baba Falooda (Kurla)",
      uuid: "384970ad-6ed8-455a-acf6-5493551f5893",
      city: "5",
      area: "Kurla",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "ys88tnnklqgfhzsftmqq",
      cuisines: ["Ice Cream", "Beverages", "Desserts"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: "47 MINS",
      lastMileTravel: 1,
      slugs: {
        restaurant: "baba-falooda-by-hotel-sky-way-powai-powai",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "TAYYAB MANZIL shop no 1,2,3 L.B.S Marg KURLA WEST MUMBAI 400070",
      locality: "Powai",
      parentId: 38827,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1 kms",
      hasSurge: false,
      sla: {
        restaurantId: "355806",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.4",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "78036",
      name: "Burger King",
      uuid: "c04163ad-ab93-4fce-81da-e87d4f2687b0",
      city: "5",
      area: "Santacruz East",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      cuisines: ["Burgers", "American"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 40,
      minDeliveryTime: 40,
      maxDeliveryTime: 40,
      slaString: "40 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "burger-king-cst-road-scruz-bandra-east",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "unit no G2, Ground floor , Central Plaza , 166,CST Road, Kalina, Mumbai 400098",
      locality: "Central Plaza, Kalina",
      parentId: 166,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "EVERY ITEM",
        subHeader: "@ ₹129",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "78036",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "299634",
      name: "YouMee",
      uuid: "9139c41d-330b-4ab5-9a52-522e804a68e2",
      city: "5",
      area: "Sakinaka",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "mcdxyl1ejqo0cu23dnc0",
      cuisines: ["Pan-Asian", "Japanese", "Sushi", "Thai", "Chinese"],
      tags: [],
      costForTwo: 90000,
      costForTwoString: "₹900 FOR TWO",
      deliveryTime: 80,
      minDeliveryTime: 80,
      maxDeliveryTime: 80,
      slaString: "80 MINS",
      lastMileTravel: 7,
      slugs: {
        restaurant: "you-mee-andheri-east-marol-sakinaka",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "Mehra Centre, Plot No 5, Marwah Estate Kishanlal Marwah Marg Sakinaka,Opposite Tata Power Gate No 4, Andheri -400072 Mahrashtra",
      locality: "Kishanlal Marwah Marg",
      parentId: 8403,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 7600,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 7600,
        message: "",
        title: "Delivery Charge",
        amount: "7600",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7252989~p=4~eid=00000189-211a-d4dc-2f43-c8a800c70413~srvts=1688477553884",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "299634",
        deliveryTime: 80,
        minDeliveryTime: 80,
        maxDeliveryTime: 80,
        lastMileTravel: 7,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.4",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "32399",
      name: "McDonald's",
      uuid: "50a56a02-357f-4041-a250-478dc74a7868",
      city: "5",
      area: "Santacruz East",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 49,
      minDeliveryTime: 49,
      maxDeliveryTime: 49,
      slaString: "49 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "mcdonalds-kalina-artista-scruz-bandra-east",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "Hardcastle Restaurants Pvt Ltd, McDonalds Family Restaurants Pvt Ltd, Sumit Artista, G-28, Vidya Nagari Rd, Mathuradas Colony, Kalina, Santacruz East, Mumbai, Maharashtra 400098.",
      locality: "Kalina Artista",
      parentId: 630,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      sla: {
        restaurantId: "32399",
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "106763",
      name: "Rangoon Zaika",
      uuid: "cd078e24-0fae-46d9-9e45-ccedc30a0834",
      city: "5",
      area: "Kurla West",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "o5bbufmcjoqdfvtm7r1n",
      cuisines: ["Indian", "Chinese"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 58,
      minDeliveryTime: 58,
      maxDeliveryTime: 58,
      slaString: "58 MINS",
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: "rangoon-zaika-kurla-kurla",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "Shop 4B-4C, Opposite Kalpana Cinema, Beside Ansari Weight Bridge, LBS Marg, Kurla, Mumbai",
      locality: "Kurla",
      parentId: 166932,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.6 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹599",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "106763",
        deliveryTime: 58,
        minDeliveryTime: 58,
        maxDeliveryTime: 58,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
];

export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
